### PR TITLE
Replace forward slashes with windows path separators

### PR DESCRIPTION
**Pull request by Jan200101**
Before this PR Northstar mixes forward and backward slashes

```
[22:22:21] [PLUGINSYS] [info] Succesfully loaded R2Northstar/plugins\DiscordRPC.dll
```

With this PR these constants use the windows path separator (backwards slash) instead.

### CODE REVIEW

**Comment by Alystrasz** [comment]
I see classical slashes appearing in the logs:
```text
[NORTHSTAR] [info] Building KeyValues for file scripts/aisettings/npc_titan.txt
[NORTHSTAR] [info] Building KeyValues for file scripts/aisettings/npc_titan_ogre_meteor_bounty.txt
```
Is this something you plan to address in this PR?

**Comment by Jan200101** [comment]
> I see classical slashes appearing in the logs:

I don't know how we can solve these without having to process the strings.
The chain appears to go

Various Hooks -> TryReplaceFile -> CompileAssetsForFile -> TryBuildKeyValues (log info is here)

So those path more than likely come from inside the Source Engine.

**Review by Alystrasz — APPROVED** [review]
Confirmed building and running, has expected effect on modified paths.

**Comment by GeckoEidechse** [comment]
Not testing myself cause others already did. Just assuming they tested well enough :>

**Pull request merged**
