### PR TITLE
handle required mod downloadlinks

### PR DESCRIPTION
**Pull request by uniboi**
broadcasts links to the masterserver and makes them available for the client
depends on R2Northstar/NorthstarMasterServer#58 and R2Northstar/NorthstarMods#309

### CODE REVIEW

**Comment by iCrazyBlaze** [comment]
This would be perfect! I hate having to manually install everything and then manually uninstall/disable when I play on another server.

**Comment by uniboi** [comment]
@iCrazyBlaze This PR doesn't implement automatic mod downloads. Only a menu is shown that links to the download pages missing mods have specified. If you're looking for automatic mod enabling/disabling, I made another PR for that here: R2Northstar/NorthstarMods#298

**Review by EladNLG — APPROVED** [review]
Clean code

10/10 would merge if I could

Also, resolve merge conflicts on the other northstarlauncher PR :3

**Comment by uniboi** [comment]
succeeded by automatic mod downloads that will come at some point in this century

**Pull request closed without merging**
