### PR TITLE
add disable logging files

### PR DESCRIPTION
**Pull request by Xavierhorwood**
does what #23 wants

### CODE REVIEW

**Comment by abarichello** [comment]
I tried testing your patch but it crashes my game on launch for some reason

**Comment by Xavierhorwood** [comment]
> I tried testing your patch but it crashes my game on launch for some reason

I will look it to that

**Comment by Xavierhorwood** [comment]
> I tried testing your patch but it crashes my game on launch for some reason

ok so I found the issue with the crash and I am working on a fix

**Comment by Xavierhorwood** [comment]
> 

I have fixed the crash but I had to remove the feature to disable dump files to fix the crash

**Comment by abarichello** [comment]
Hey, your patch wasn't working because you need to check command line args after hooks are loaded. I created another commit (https://github.com/R2Northstar/NorthstarLauncher/commit/c9d66513a85d5325d3d002ca16c82d8302ec0ea2) to fix #23

**Pull request closed without merging**
