### PR TITLE
Disable run_northstar.txt using preprocessor

### PR DESCRIPTION
**Pull request by Jan200101**
Related to #508 

Disables `run_northstar.txt` logic via preprocessors.

The main use case for it has mostly been Linux where steam_helper incorrectly handled arguments.

With NorthstarProton and GE-Proton containing a patch to fix the bug this is mostly a non issue these days.

### CODE REVIEW

**Comment by ASpoonPlaysGames** [comment]
Why disable using preprocessor instead of commenting/deleting the lines?

**Comment by Jan200101** [comment]
Advised as a first step by iirc Gecko to make it easy to reenable if someone comes out of nowhere and gives a good reason to keep this.

**Comment by ASpoonPlaysGames** [comment]
Fair enough

**Review by ASpoonPlaysGames — APPROVED** [review]
Code looks good

**Comment by ASpoonPlaysGames** [comment]
Note for testing: probably best to test on Linux?

**Review by Alystrasz — APPROVED** [review]
Code looks good and works as intended on Windows: putting a `0` inside the `run_northstar.txt` file does not prevent Northstar from launching anymore.

**Pull request closed without merging**
