### PR TITLE
Fix module callbacks related crash

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
Hopefully fixes crash related to #780

draft until verified as fixed

### CODE REVIEW

**Comment by Gazyi** [comment]
Doesn't crash with https://github.com/R2Northstar/NorthstarLauncher/pull/790/commits/f21f2dd677e2773e7c2abf69cb62b0cc234b61cc applied.
`m_pNTHeaders->FileHeader.SizeOfOptionalHeader` returns non-zero.

**Comment by ASpoonPlaysGames** [comment]
Newest commit should also not crash hopefully

**Comment by GeckoEidechse** [comment]
@Gazyi can you retest? :point_right::point_left:

**Comment by Gazyi** [comment]
> Newest commit should also not crash hopefully
No crashes on launch and in-game. It's good now.

**Review by F1F7Y — APPROVED** [review]
Changes look fine ( although line wrapping on mobile don't )

**Pull request merged**
