### PR TITLE
Update libcurl and remove openssl dependency

### PR DESCRIPTION
**Pull request by BobTheBob9**
Updates `libcurl` to version `7.87.0` (with websocket support) built with winssl for ssl support, also removes openssl as it is not currently required for any code or as a dependency for any libs we use

### CODE REVIEW

**Review by GeckoEidechse — APPROVED** [review]
No issues in testing on Win8,1 when
- Authing with MS
- Joining a random Northstar server

Did not test hosting a server.

**Comment by GeckoEidechse** [comment]
cc @Erlite cause this is a step towards "WebSockets from Squirrel" (#372)

**Comment by pg9182** [comment]
Needs to be tested on Docker, but I'm busy rn.

**Review by pg9182 — COMMENTED** [review]
Please document how the libcurl lib is built so we have it for future reference.

**Review by GeckoEidechse — APPROVED** [review]
Confirmed working on:
- Windows dedi
- Linux Docker using `ghcr.io/pg9182/northstar-dedicated:1-tf2.0.11.0-ns1.12.0` https://github.com/pg9182/northstar-dedicated-ci/actions/runs/4108401748

**Comment by BobTheBob9** [comment]
> Please document how the libcurl lib is built so we have it for future reference.

Downloaded latest libcurl source, used the vc14.30 project in libcurl/projects to build with the options "LIB Release - DLL Windows SSPI" in x64

**Comment by pg9182** [comment]
WinSDK version, @BobTheBob9?

**Review by pg9182 — CHANGES_REQUESTED** [review]
Need to investigate this (probably just some missing libs):

```
ns-aitdm_dev_local-1  | [13:48:50] [NORTHSTAR] [info] SERVER CodeCallback CodeCallback_PostEntityInit called
ns-aitdm_dev_local-1  | [13:48:50] [NORTHSTAR] [info] Not executing custom callbacks for CodeCallback CodeCallback_PostEntityInit
ns-aitdm_dev_local-1  | [13:48:50] [SCRIPT SV] [info] Code Script: _init
ns-aitdm_dev_local-1  | [13:48:50] [NATIVE SV] [info] Created new format snapshot class baseline with 78 classes, 7601 properties and 36KB of prop data.
ns-aitdm_dev_local-1  | [13:48:50] [NORTHSTAR] [info] loading took 16.070063299999997s
ns-aitdm_dev_local-1  | [13:48:50] [NORTHSTAR] [info] Attempting to register the local server to the master server.
ns-aitdm_dev_local-1  | [13:48:50] [NORTHSTAR] [errr] Failed adding self to server list: error SSL connect error
ns-aitdm_dev_local-1  | [13:48:50] [NORTHSTAR] [errr] Reached max ms server registration attempts.
```

**Update:** Did a build with full wine, and it's still acting weird... going to try on a different machine.
**Update:** WTF, it worked... will debug further.
**Update:** The current release works fine on the first machine tho.
**Update:** And so does the commit before this PR.
**Update:** Tried rebuilding the image, and it's still not working on one, but working on the other...
**Update:** Same thing on another machine.

**Comment by BobTheBob9** [comment]
> WinSDK version, @BobTheBob9?

10.0.0

**Comment by GeckoEidechse** [comment]
Merge conflicts now btw

**Comment by GeckoEidechse** [comment]
Re-opened cause the PR that closed it was reverted. That being said I expect this PR here to be closed again once #500 is merged.

Mostly treating this PR here as an issue to keep track of what to do :P

**Comment by GeckoEidechse** [comment]
Re-opened cause the PR that closed it was reverted. That being said I expect this PR here to be closed again once #500 is merged.

Mostly treating this PR here as an issue to keep track of what to do :P

**Pull request closed without merging**
