### PR TITLE
Add clang-format config to pack constructor initializers

### PR DESCRIPTION
**Pull request by uniboi**
This is how it currently looks:
```c++
Plugin::Plugin(HMODULE lib, int handle, std::string identifier)
	: name(GetSymbolValue<char*>(lib, Symbol::NAME)), logName(GetSymbolValue<char*>(lib, Symbol::LOG_NAME)),
	  dependencyName(GetSymbolValue<char*>(lib, Symbol::DEPENDENCY_NAME)), description(GetSymbolValue<char*>(lib, Symbol::DESCRIPTION)),
	  api_version(GetSymbolValue<uint32_t>(lib, Symbol::REQUIRED_ABI_VERSION)), version(GetSymbolValue<char*>(lib, Symbol::VERSION)),
	  handle(handle), runOnContext(GetSymbolValue<uint8_t>(lib, Symbol::CONTEXT)), run_on_client(runOnContext & PluginContext::CLIENT),
	  run_on_server(runOnContext & PluginContext::DEDICATED), init(GetSymbolValue<PLUGIN_INIT_TYPE>(lib, Symbol::INIT)),
	  init_sqvm_client(GetSymbolValue<PLUGIN_INIT_SQVM_TYPE>(lib, Symbol::CLIENT_SQVM_INIT)),
	  init_sqvm_server(GetSymbolValue<PLUGIN_INIT_SQVM_TYPE>(lib, Symbol::SERVER_SQVM_INIT)),
	  inform_sqvm_created(GetSymbolValue<PLUGIN_INFORM_SQVM_CREATED_TYPE>(lib, Symbol::SQVM_CREATED)),
	  inform_sqvm_destroyed(GetSymbolValue<PLUGIN_INFORM_SQVM_DESTROYED_TYPE>(lib, Symbol::SQVM_DESTROYED)),
	  inform_dll_load(GetSymbolValue<PLUGIN_INFORM_DLL_LOAD_TYPE>(lib, Symbol::LIB_LOAD)),
	  run_frame(GetSymbolValue<PLUGIN_RUNFRAME>(lib, Symbol::RUN_FRAME)),
	  valid(api_version && name && description && version && init && logName && runOnContext)
{}
```

The setting will set each initializer in a new line if all of them don't fit in one line
image

### CODE REVIEW

**Comment by uniboi** [comment]
What clang-format version is the workflow using

**Comment by GeckoEidechse** [comment]
> The workflow is using clang-format 13 but that setting is only available in 14+

You need to update the value here ig

https://github.com/R2Northstar/NorthstarLauncher/blob/da7061a846759cd63dd1907a9df163f4c5b17cf6/.github/workflows/ci.yml#L49C31-L49C31

**Comment by GeckoEidechse** [comment]
Actually, we should probably also update the action version to like `0.16` or something ^^

**Comment by uniboi** [comment]
sure

**Pull request merged**
