### PR TITLE
Replace `NOTE_UNUSED` with standard `[[maybe_unused]]` attribute

### PR DESCRIPTION
**Pull request by Jan200101**
Replaces the `NOTE_UNUSED` macro with the standardized `[[maybe_unused]]` attribute.

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Tagging @ASpoonPlaysGames who introduced `NOTE_UNUSED()`. This might be of interest to you. I only learned about this with this PR too :eyes:

**Review by ASpoonPlaysGames — COMMENTED** [review]
A lot of these variables are always unused. Using  `maybe_unused` for them seems incorrect. 

`maybe_unused` afaik is meant for variables that are used under some build configurations, but not all.


I think I maybe prefer `int /*name*/` for always unused parameters, and `maybe_unused` for conditionally used ones? Open to suggestions though

**Comment by Jan200101** [comment]
this is nothing more than `NOTE_UNUSED` but as an attribute instead of within the code to give the compiler a hint.

**Comment by ASpoonPlaysGames** [comment]
Functionally, yes. But using the standard attribute means that we should really follow best practice with it

**Pull request closed without merging**
