### PR TITLE
Always allow the local player through the banlist

### LINKED ISSUE #163: Hosting a dedicated server and banning yourself prevents you from opening lobby
### Bug
Not sure if this is a bug at all, but something I discovered while playing around with https://github.com/R2Northstar/Northstar/issues/251.

If the server files are in the same folder as the game files, banning yourself from the server, bans you from the main lobby.

To my understanding, this happens because the [banlist is checked every time](https://github.com/R2Northstar/NorthstarLauncher/blob/6c8112a6c368dd36d21fd94689e9682bc3b012a5/NorthstarDedicatedTest/serverauthentication.cpp#L370) a user connects (and you connect to the lobby) and since you are in that list, you get banned.

### Steps to reproduce
  1. Start dedicated server
  2. ban yourself
  3. Restart the game
  4. Try to join the lobby

### Specifications
  - Northstar version: 1.7.0
  - Platform: Origin

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
closes #163

The local player (host) should be exempt from the banlist. Note that this doesn't remove the local player through the banlist, it simply doesn't check if they are banned or not

### CODE REVIEW

**Comment by Alystrasz** [comment]
I didn't know Northstar had an integrated banlist mechanism :smile:
How can this be tested?

**Comment by ASpoonPlaysGames** [comment]
Get your own UID and add it to `banlist.txt`, then try to go into the lobby

**Comment by Alystrasz** [comment]
> Get your own UID and add it to `banlist.txt`, then try to go into the lobby

* How can I get my own UID?
* Where's that `banlist.txt` file?

**Review by Alystrasz — APPROVED** [review]
Code looks good, and works as expected.
Connection is possible even if local player ID is in the banlist.

#### Screenshots

###### Without PR

image

###### With PR

Connection works as expected:

image

**Comment by GeckoEidechse** [comment]
Merging based on reviews.

**Pull request merged**
