### PR TITLE
Add log colours because they are pretty

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
image

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Soo pwetty :eyes: 

I assume colour is only written to in console and we don't get any ANSI colour escape characters in logfile, right? ^^

**Comment by ASpoonPlaysGames** [comment]
> I assume colour is only written to in console and we don't get any ANSI colour escape characters in logfile, right? ^^

image
Not 100% sure that this is the correct log, but all of the ones i have around the time i made the pr and uploaded that image are the same, no ANSI colour escape chars in sight as far as i can tell

**Comment by GeckoEidechse** [comment]
So turns out colour printing doesn't seem to work on Windows 8.1 xD
It just prints in the usual white.

So I need someone on 10/11 to test to confirm this as working :,D

**Review by Alystrasz — APPROVED** [review]
Tested on Windows 10.
LGTM

**Review by GeckoEidechse — APPROVED** [review]
Colours confirmed working when testing on Windows 8.1 :3

**Comment by GeckoEidechse** [comment]
Also confirmed again, no ANSI colour codes or similar in text logs ^^

**Comment by GeckoEidechse** [comment]
Reverted in `v1.9.6` due to causing some issues with client freezes, mostly related to Viper. The exact cause is still unknown.

**Pull request merged**
