### PR TITLE
Fix stringcmd limits causing unnecessary disconnects

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
reverts some changes made by #411 , specifically to do with replacing Plat_FloatTime

Explanation of why this was a problem yoinked from discord
image

should fix
- https://github.com/R2Northstar/Northstar/issues/448

maybe also fixes
- https://github.com/R2Northstar/Northstar/issues/449 
- https://github.com/R2Northstar/Northstar/issues/450

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
@BobTheBob9 as an fyi

**Review by GeckoEidechse — APPROVED** [review]
This was tested and confirmed to resolve issues on servers via

https://github.com/pg9182/northstar-dedicated-ci/actions/runs/4640641725

Confirmed by @NoCatt and @Legonzaur

**Comment by wolf109909** [comment]
cool

**Comment by MarcusUA** [comment]
I'm now getting many 'Disconnect: Sent too many stringcmd commands.' after updating to 1.12.5 today.
was playing Frontier Defense and got like 4 disconnects with above error. Didn't get any disconnects yesterday on 1.12.4
Should I open new issue?

**Comment by wolf109909** [comment]
> I'm now getting many 'Disconnect: Sent too many stringcmd commands.' after updating to 1.12.5 today. was playing Frontier Defense and got like 4 disconnects with above error. Didn't get any disconnects yesterday on 1.12.4 Should I open new issue?

Can you try increasing the convar `sv_quota_stringcmdspersecond` to about 80 and test it again?

**Comment by MarcusUA** [comment]
No, I'm not server owner, I didn't realize it could be on server side, I guess it could be that server was not updated yet.

**Comment by uniboi** [comment]
Server owners try to update their servers challenge (impossible)

**Pull request merged**
