### PR TITLE
Don't build when format check failed

### PR DESCRIPTION
**Pull request by Jan200101**
This will prevent needless CI running when the format is all wack

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
This is kinda on purpose so that we can easily test PR builds even if PR author managed to mess up formatting.

I'm fine with changing it though if desired ^^

**Comment by Jan200101** [comment]
I guess?
but considering the nature of a pull request, it should have the right format already.
Idk, leaving this up to someone else to decide.

**Comment by Alystrasz** [comment]
I agree with this change, let's not encourage authors not to format their code!

**Comment by GeckoEidechse** [comment]
Just to be clear, PRs are already blocked from being merged until they are properly formatted. This change would just block PRs from being tested while they are still improperly formatted ^^

**Pull request closed without merging**
