### PR TITLE
Initial CMake mingw-w64 port

### PR DESCRIPTION
**Pull request by mrsteyk**
This PR allows to build everything except NorthstarDLL using CMake+mingw-w64 under a Linux host.

- [ ] Port NorthstarDLL (requires OpenSSL, libcurl)

### CODE REVIEW

**Comment by mrsteyk** [comment]
currently requires you to ship
```
libwinpthread-1.dll
libstdc++-6.dll
libgcc_s_seh-1.dll
```

If you use static flags it makes every single file be 17MiB in RelWithDebInfo...

**Comment by pg9182** [comment]
We were going to do this with meson and mingw-w64 with msvc (see NorthstarStubs and some of the discussions on Discord).

**Comment by GeckoEidechse** [comment]
You still working on this? :>

**Comment by GeckoEidechse** [comment]
Closing as outdated and stale.

**Pull request closed without merging**
