### PR TITLE
Fix plugins not loading

### PR DESCRIPTION
**Pull request by F1F7Y**

### CODE REVIEW

**Comment by Jan200101** [comment]
Fixes regression added with 09bb27c0590fc3ad0a5a35230acaf4586aa1b466

**Review by Jan200101 — APPROVED** [review]
Code looks good, Klemmbaustein tested and said it works.

**Review by JMM889901 — APPROVED** [review]
Worky :)

**Comment by GeckoEidechse** [comment]
Fixes a regression introduced in #513

**Pull request merged**
