### PR TITLE
Fix crash when running `disconnect %%s`

### LINKED ISSUE #552: Running `disconnect` with string format specifiers does weird things
Examples:
`disconnect %s` shows the following in the error dialog
image
`disconnect "%n"` causes this assert:
image

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
Closes #552 

Basically we were running a string format and then passing the string to the original function, which would then try and format it again (and get bad args). By passing `"%s"` and then our formatted string we basically just protect the vanilla string format

### CODE REVIEW

**Comment by Mauler125** [comment]
Code looks good, should be merged as this will fix potential security problems from taking place in the engine.
A further analysis of the code base is recommended for uncontrolled format strings or similar code bugs (requires /Wall to see).

**Comment by ASpoonPlaysGames** [comment]
Whoever merges this should add @Mauler125 as coauthor :)
(I forgot when making the commit)

**Review by F1F7Y — APPROVED** [review]
Works, changes look good.

Preferably #553 should be implemented

**Review by Alystrasz — APPROVED** [review]
Running `disconnect %%s` does not crash the client with this.

**Review by GeckoEidechse — APPROVED** [review]
Confirmed working in testing by running `disconnect %%s` with and without the PR (with prints `%s`, without crashes). No code review done.

**Comment by GeckoEidechse** [comment]
> Whoever merges this should add @Mauler125 as coauthor :)
> (I forgot when making the commit)

Done o7

**Pull request merged**
