### PR TITLE
Use strtoull instead of strtoll for uint64s

### PR DESCRIPTION
**Pull request by KittenPopo**
I have no proof that this will actually ever cause a real problem, but it's definitely a good idea and is more proper.

### CODE REVIEW

**Comment by KittenPopo** [comment]
> Note to self:
> 
> * `strtoll`: Convert string to long long integer
> * `strtoull`: Convert string to _unsigned_ long long integer

`strtoll` = `str to L L (long long)`
`strtoull` = `str to U L L (unsigned long long)`
`strtoul` = `str to L (long/int)`

Once you realize the pattern its pretty helpful xD

**Comment by GeckoEidechse** [comment]
To hit those lines in testing I assume I just to put someone on banlist and then have them join server? ^^

**Comment by KittenPopo** [comment]
> To hit those lines in testing I assume I just to put someone on banlist and then have them join server? ^^

... Yes. 

Not sure why a 1-character function usage switch of a super common STL function needs testing, but go for it xD

**Comment by GeckoEidechse** [comment]
> > To hit those lines in testing I assume I just to put someone on banlist and then have them join server? ^^
> 
> ... Yes.
> 
> Not sure why a 1-character function usage switch of a super common STL function needs testing, but go for it xD

Eh, like the issue is not gonna be in a standard lib function. More so in the change from one function to the other. And like I don't expect anything to break either. It's mostly about establishing a pattern of testing every PR for the stuff it changes.

Anyway, noticed no issues in testing ^^

**Pull request merged**
