### PR TITLE
Reduce warnings due to calling conventions

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
Removes `C4229 "anachronism used: modifiers on data are ignored"` warnings

Reduces warning count from 82 to 6

image

## Testing:
Literally just play the game for a bit, load some mods, see if you notice any new crashes?

### CODE REVIEW

**Review by Alystrasz — COMMENTED** [review]
I don't get the code changes introduced by this PR, but I played a few games (pilots and titans) with no problem.

**Comment by GeckoEidechse** [comment]
@ASpoonPlaysGames what would be a good way to test this? Just play the game and hope everything works? ^^"

**Comment by ASpoonPlaysGames** [comment]
> @ASpoonPlaysGames what would be a good way to test this? Just play the game and hope everything works? ^^"

Pretty much, yeah

**Review by Jan200101 — APPROVED** [review]
PR just removes calling convention from a bunch of places, which is fine.

Does indeed get the build warnings down to 6.

Tested a bit on the Crazy Gungame server and it worked without a problem.

**Comment by GeckoEidechse** [comment]
Merging based on previous reviews.

**Pull request merged**
