### PR TITLE
Remove Vector3 Constructor

### PR DESCRIPTION
**Pull request by Jan200101**
Packing was enabled because the compiler may add padding which we don't want.

Constructors were removed because they were either rather primitive or broken (the `pRawFloats` one).

Use of constructor was replaced with a simple cast, which works just as well.

### CODE REVIEW

**Comment by Jan200101** [comment]
After spending a few seconds with the compiler explorer
I came to the conclusion that packing is entirely pointless here, so I'm removing it.

I'll also merge the CI correction commit into the main one and rebase, for the sake of clarity.

**Review by Alystrasz — APPROVED** [review]
Confirmed building and running.

**Review by uniboi — APPROVED** [review]
Code looks good & fixes an incorrect allocation

**Comment by GeckoEidechse** [comment]
Not testing myself cause others already did. Just trusting they tested well enough :>

**Pull request merged**
