### PR TITLE
Set `spewlog_enable` default value to 0

### PR DESCRIPTION
**Pull request by F1F7Y**
Closes [#506](https://github.com/R2Northstar/Northstar/issues/506)

Would like to add a launch arg in the future ( smth like `-nsdev` ) that would enable all log funcs and other features.

This log call can sometimes slow the game down

### CODE REVIEW

**Comment by ASpoonPlaysGames** [comment]
Which logs exactly does this disable? my guess would be the `NATIVE SV` (and other VM ones) but not 100% sure. We need to make sure that nothing that may prove useful for tickets and such is getting disabled

**Comment by F1F7Y** [comment]
> Which logs exactly does this disable? my guess would be the `NATIVE SV` (and other VM ones) but not 100% sure. We need to make sure that nothing that may prove useful for tickets and such is getting disabled

Only the `NATIVE SV` ones

**Review by ASpoonPlaysGames — APPROVED** [review]
Code looks good (lol)

no `[NATIVE SV]` logging is seen in the console or in log files with `spewlog_enable` set to 0

**Review by GeckoEidechse — COMMENTED** [review]
Merging based on previous reviews.

**Pull request merged**
