### PR TITLE
feat: Verified mods auto-downloading

### PR DESCRIPTION
**Pull request by Alystrasz**
This pull request introduces automatic mods fetching.

`NorthstarMods` associated pull request: https://github.com/R2Northstar/NorthstarMods/pull/542

---

This allows for the client to download and install mods that are required by a server (client+server-side mods, like new game mods or maps for instance). List of verified mods is local (compiled in the dll), but it can be fetched from master server in the future, to ease the addition of new verified mods.

With this feature, if users want to join a server requiring a gamemode mod or a map mod, their game can automatically download it for them, instead of forcing them to go through manual mod installation process (which can be hard for some people). While downloading a mod, progress download is displayed and live-updated on a dialog pop-up.

## Verified mod entries

A verified mod entry looks like this:

```json
{
    "Fifty.mp_frostbite": {
        "DependencyPrefix": "Fifty-Frostbite",
        "Versions": [
            { "Version": "0.0.1", "Checksum": "99fc4f0b3363e44985f20525a2bf079..." },
            { "Version": "0.0.2", "Checksum": "40780308e0e4a70f7f35f50f2ca188a..." }
        ]
    }
}
```

Versions are checked individually to ensure no malicious code has been added during mod updates.

Please note that it is up to the community to decide what's needed for a mod to be "verified", and how such mod is "verified".

Discussion here: https://github.com/R2Northstar/VerifiedMods

## Mod installation process

1. Check if mod is verified
    a. Check if it is listed
    b. Check if version is listed
2. Download mod archive from Thunderstore
    a. Fetch zip from API
    b. Compare checksum with local checksum
3. Unzip mod archive content directly into game folder
4. Reload mods list
5. Remove downloaded archive

Please note that downloaded archive is checksumed, to verify it is the very archive that has been verified.

#### `Northstar.Client`

* `OnServerSelected` method becomes async, to allow waiting for mod verification;
* `_OnServerSelected` method now displays some dialogs:
  * One error message when one attemps to join a server requiring a mod which cannot be auto-downloaded;
  * One loading message, displaying while a verified mod is being downloaded;
  * One error message when mod downloading/extraction failed;
* If a needed mod is already present but disabled, this activates it.

#### `Launcher`

* Includes a new library, `libzip`
* Includes the already-included but not linked `openssl` lib;
* All verified-mods-related code is stored in `verifiedmods.cpp`
* Squirrel-exposed methods:
  * `bool NSIsModVerified(string modName, string modVersion)`\: tells if a mod is verified or not;
  * `void NSDownloadMod(string modname, string modVersion)`\: starts downloading a mod; returns nothing because actual mod downloading is done in a thread, as not to block UI;
  * `bool NSIsModBeingDownloaded(string modName)`\: tells if a mod is being downloaded; this is used by UI to check if it should display loading dialog to the user;
  * `float NSGetCurrentDownloadProgress()`\: returns progression in percentage of current download/extraction;
  * `string NSGetModExtractionResult()`: returns result of mod download/extraction;

## Testing

I tested this PR with two mods:

* `Juicy.Zircon_Spitfire`, a HUGE (1.7GB) skin mod (set as client-required for the sake of testing this);
*  `Fifty.mp_frostbite`, a map mod.

Maps mods are a good example of mods that would benefit from auto-downloading, because they are required on both client and server sides.

###### If mod is not verified

Mod not verified

###### If something goes wrong during mod download/extraction

mod_extraction_error_dialog

###### If mod is verified

Mod extraction with progress based on extracted bytes count

[verified_download_s2space.webm](https://github.com/R2Northstar/NorthstarLauncher/assets/11993538/e5db912c-057c-46a1-9c9e-f66b07687ab5)

## TODOs

- [ ] Build issues **(to make this work, I had to put `zip.dll`, `bzip.dll` and `libzip.dll` into game folder, but those are not generated sometimes, gotta find why)**
    - [ ] Maybe integrate [miniz](https://github.com/richgel999/miniz) instead of libzip
- [ ] Add libzip licence (will do once this is actually merged)
- [x] Handle errors while downloading/extracting
- [x] Verify checksums
- [x] Test with bigger mods (we may need a progress indicator for big maps for instance)
    - [x] Test with bigger mods
    - [x] Add a progress indicator
- [x] Clean downloaded files
- [x] Mod managers support
    - [x] Save `manifest.json` and put it in mod directory
    - [x] Put a `"AutoDownloaded": true` entry into `mod.json`

### CODE REVIEW

**Comment by ASpoonPlaysGames** [comment]
failing build D:

**Comment by Alystrasz** [comment]
> failing build D:

That's only formatting issues, and more importantly, `libzip` library import which doesn't work (dlls are not properly generated on my laptop)

**Comment by GeckoEidechse** [comment]
Where do you store the zip file while it's being downloaded/extracted? ^^

**Comment by Alystrasz** [comment]
> Where do you store the zip file while it's being downloaded/extracted? ^^

The downloaded archive is stored in a temporary directory, be it `AppData/Local/Temp` on Windows or `/tmp` on UNIX systems.

**Comment by DxsSucuk** [comment]
Unsure if it has been discussed why not allow users to download it even if it is not verified?
You could display a message activily warning the user that the mod is not verified and that downloading it could cause Issues.

**Comment by uniboi** [comment]
Untreated paranoid schizophrenia from some developers

**Comment by DxsSucuk** [comment]
It would make it more user friendly and allow developers to make their maps and gamemodes accessible just as easy as verified developers, just with the note that some users would not use it because they want to be sure they can trust it.

In this scenario the verified state can be used as some sort of "guide" for users that are new to Northstar and are scared that they could break something or something else. And at the same time allow users that trust the resource to download it without doing it manually which allows them to save the hussle of manually doing it.

**Comment by ASpoonPlaysGames** [comment]
Other than potential security problems with doing this, northstar mods do not have any link to a thunderstore package, as a thunderstore package can contain multiple northstar mods (as well as plugins which are compiled dlls, not something you want to autodownload without verification). This means that without the verified mods listings bridging that gap, there is no way for a client to find the correct download link. You could ask modders to put this in the mod.json somewhere, network it to masterserver and then back to clients, but there would be nothing stopping the modder from linking the wrong thunderstore package dependency string, or simply packaging a malicious plugin in the package that would get autodownloaded and then ran on next launch

**Comment by ASpoonPlaysGames** [comment]
> And at the same time allow users that trust the resource to download it without doing it manually which allows them to save the hussle of manually doing it.

If they can trust the resource, that implies that they have looked into it, in which case it's really not much for them to be expected to download manually

**Comment by uniboi** [comment]
> verified developers

The idea is to verify on a per mod basis, so everyone can request a mod being verified

**Comment by DxsSucuk** [comment]
> The idea is to verify on a per mod basis, so everyone can request a mod being verified
Well aware but keeping in mind that if Northstar gets alot more modders in and alot more people want to verify their mod it will take longer for the verification.

**Comment by DxsSucuk** [comment]
> > And at the same time allow users that trust the resource to download it without doing it manually which allows them to save the hussle of manually doing it.
> 
> If they can trust the resource, that implies that they have looked into it, in which case it's really not much for them to be expected to download manually

Not really for example I personally do not look at the code of mods from people that I know and personally trust (well aware that this isnt good). And as a user it would be easier and far more user friendly to let the mod be downloaded after I try to join a Server that a friend owns. 

Incase the idea with mods from server being seperated from normal ones it would be alot easier specific users might not want specific mods on their device or play with them when being with friends.

Overall Im simply suggesting a system similiar to Garry Mods, but with warnings on mods that are not verified.

**Comment by ASpoonPlaysGames** [comment]
> Not really for example I personally do not look at the code of mods from people that I know and personally trust (well aware that this isnt good). And as a user it would be easier and far more user friendly to let the mod be downloaded after I try to join a Server that a friend owns.
> 
> Incase the idea with mods from server being seperated from normal ones it would be alot easier specific users might not want specific mods on their device or play with them when being with friends.
> 
> Overall Im simply suggesting a system similiar to Garry Mods, but with warnings on mods that are not verified.

This still has the problem of no Northstar mod -> Thunderstore package connection, as it is a many-to-one relationship

**Comment by Alystrasz** [comment]
> Unsure if it has been discussed why not allow users to download it even if it is not verified?

Basic theorem in IT: users are stupid. 

From a developer point of view, they will always do stuff you don't expected them to do in any ways, including willingly downloading malware on their computers; we have a rather small community of players with Northstar, so I don't think we can afford a scandal like [colors.js](https://www.google.com/amp/s/securityboulevard.com/2022/12/npm-libraries-colors-and-faker-sabotaged-in-protest-by-their-maintainer-what-to-do-now/amp/).

**Comment by GeckoEidechse** [comment]
> > The idea is to verify on a per mod basis, so everyone can request a mod being verified
> 
> Well aware but keeping in mind that if Northstar gets alot more modders in and alot more people want to verify their mod it will take longer for the verification.

Time to verify will definitely become a bottleneck hence "verification" will be limited to mods that need to be auto-downloadable, e.g. custom gamemodes or custom maps. A gun reskin or a custom model is currently not planned to ever be verified.

> You could display a message activily warning the user that the mod is not verified and that downloading it could cause Issues.

It's basically guaranteed that user will just click past the warning. And knowing that we have certain individuals that love to attack this project, we don't want to give them any more opportunities to do so than absolutely necessary. If a player gets pwned cause they (auto-)downloaded a malicious mod, people will start pointing their fingers at Northstar as opposed to the player when looking for who to blame.

If you want an easy way to install mods, we have more then enough between [Viper](https://github.com/0neGal/viper), [VTOL](https://github.com/R2NorthstarTools/VTOL), [r2mm](https://github.com/ebkr/r2modmanPlus), and [FlightCore](https://github.com/R2NorthstarTools/FlightCore/) :P

**Comment by Alystrasz** [comment]
Ok so I would like to get some reviews on this already-existing code basis, even if it needs to be reworked after whole mod system rework (see issue https://github.com/R2Northstar/NorthstarLauncher/issues/396).

---

##### How to test?

1. Use the `Northstar.Client` mod from this PR (https://github.com/R2Northstar/NorthstarMods/pull/542);
2. Build launcher files from `NorthstarLauncher` PR (https://github.com/R2Northstar/NorthstarLauncher/pull/362) and move them to your game folder;
3. Launch game (if you're missing DLLs, [you can download them here](https://cloud.remyraes.com/s/DncofkRWYRzEW8X));
4. Try to join "Alystrasz's realm" server, you should see mods being downloaded before you join the server.

**Comment by Alystrasz** [comment]
Last changes:
* As of 27350a9, downloaded mods are extracted in remote mods directory (`runtime/remote/mods`);
* As of 0e322ea, Thunderstore dependency string is used to name mods folders.

image

**Comment by GeckoEidechse** [comment]
> 3\. Launch game (if you're missing DLLs, [you can download them here](https://cloud.remyraes.com/s/DncofkRWYRzEW8X));

Might be worth specifying where to put them (i.e. in same folder as `Northstar.dll`) ^^

**Comment by Alystrasz** [comment]
> Might be worth specifying where to put them (i.e. in same folder as `Northstar.dll`) ^^

Indeed! I edited the original post.
(and I would love for somebody to find out how to include those dlls into `Northstar.dll` or something alike, for not having to copy-paste them)

**Comment by GeckoEidechse** [comment]
From quick testing I noticed that `Zircon_Spitfire` specified in the PR was not getting disabled on server leave but `Frostbite` did. Note sure what's up with that.

Otherwise seems to work fine. Tried to join your server, it downloaded the mods, then joined it. Might make sense to set the server to a mod where being able to join implies that mod download worked. I think the LTS community have a bunch that are required on client and server. Maybe https://northstar.thunderstore.io/package/Dinorush/DinorushBrute4/ ?

> - [ ] Build issues (to make this work, I had to put zip.dll, bzip.dll and libzip.dll into game folder, but those are not generated sometimes, gotta find why)

I sadly have no idea how to do that maybe ping @BobTheBob9 ?

> - [ ] Add libzip licence (will do once this is actually merged)

If you got nothing else to do, feel free to open the PR into release repo already so that once this PR here is ready to merge, we don't have to wait for the license PR ^^
Sample merged license PR for inspiration https://github.com/R2Northstar/Northstar/pull/314/files

**Comment by ASpoonPlaysGames** [comment]
> From quick testing I noticed that `Zircon_Spitfire` specified in the PR was not getting disabled on server leave but `Frostbite` did. Note sure what's up with that.

afaik the zircon spitfire mod isn't requiredOnClient, so i'm not sure why it's being used as an example mod for auto-downloading as it would never need to be auto-downloaded?

**Comment by Alystrasz** [comment]
> From quick testing I noticed that Zircon_Spitfire specified in the PR was not getting disabled on server leave but Frostbite did. Note sure what's up with that.

I didn't add anything mod-disabling-related, I plan to do this on another PR (tracked in https://github.com/R2Northstar/NorthstarLauncher/issues/396) as this should be done with all server-required mods, and is not specific to verified mods.

> afaik the zircon spitfire mod isn't requiredOnClient, so i'm not sure why it's being used as an example mod for auto-downloading as it would never need to be auto-downloaded?

Quite literally [quoting you](https://github.com/R2Northstar/NorthstarMods/pull/542#issuecomment-1345645718), I used Zircon as a big mod example to try out download/extraction UI progress :)

**Comment by ASpoonPlaysGames** [comment]
> Quite literally [quoting you](https://github.com/R2Northstar/NorthstarMods/pull/542#issuecomment-1345645718), I used Zircon as a big mod example to try out download/extraction UI progress :)
> But yeah, normally this kind of mod (skins) is not a good candidate for verified mods.

Ah, forgot about that tbh, been a while

**Comment by Alystrasz** [comment]
> Might make sense to set the server to a mod where being able to join implies that mod download worked. I think the LTS community have a bunch that are required on client and server. Maybe https://northstar.thunderstore.io/package/Dinorush/DinorushBrute4/ ?

Missed that part of your comment.

> Might make sense to set the server to a mod where being able to join implies that mod download worked.

Server requires Fifty's map to join, but because of the map rotation, you won't play on it :(

> I think the LTS community have a bunch that are required on client and server. Maybe https://northstar.thunderstore.io/package/Dinorush/DinorushBrute4/ ?

I can add this one to the hardcoded verified mods list. Maybe it's a good candidate to test our mod verification process? 😄

**Comment by catornot** [comment]
Does auto-download also download the dependencies?

Like [mirror city ](https://northstar.thunderstore.io/package/cat_or_not/mp_mirror_city/)relies on [Flipside ](https://northstar.thunderstore.io/package/The_Peepeepoopoo_man/FlipSide/) which is a server mod.

**Comment by GeckoEidechse** [comment]
> Does auto-download also download the dependencies?
> 
> Like [mirror city](https://northstar.thunderstore.io/package/cat_or_not/mp_mirror_city/) relies on [Flipside ](https://northstar.thunderstore.io/package/The_Peepeepoopoo_man/FlipSide/) which is a server mod.

Not sure about current implementation but in theory it should under the assumption that the dependency is verified as well ^^

**Comment by Alystrasz** [comment]
> Not sure about current implementation but in theory it should under the assumption that the dependency is verified as well ^^

Currently, I check the list of required mods that is exposed by the server; I'm unsure if Flipside would be included in the list in that case?

**Comment by catornot** [comment]
> > Not sure about current implementation but in theory it should under the assumption that the dependency is verified as well ^^
> 
> Currently, I check the list of required mods that is exposed by the server; I'm unsure if Flipside would be included in the list in that case?

Flipside wouldn't be included because its only a server side mod. In this case it doesn't matter since its server side.
but if I where to make my mods depend on client side utils mods, that would produce compile errors

**Comment by Alystrasz** [comment]
> Might make sense to set the server to a mod where being able to join implies that mod download worked. I think the LTS community have a bunch that are required on client and server. Maybe https://northstar.thunderstore.io/package/Dinorush/DinorushBrute4/ ?

I added this mod both to the client list of verified mods and to the list of required mods on my server, so it can be auto-downloaded.

> Flipside wouldn't be included because its only a server side mod. In this case it doesn't matter since its server side.
but if I where to make my mods depend on client side utils mods, that would produce compile errors

This will definitely be an issue. Should we force including mods' dependencies into required mods server lists as well?

**Comment by EladNLG** [comment]
IMO, a simple solution for this would be "for your mod to get verified, it's dependencies also have to be verified."

**Comment by GeckoEidechse** [comment]
> IMO, a simple solution for this would be "for your mod to get verified, it's dependencies also have to be verified."

Agreed. We should check both when verifying the mod as well as in launcher when it pulls in the mod dependencies in case we had a slip up.

**Comment by Alystrasz** [comment]
Agreed too!
I'll add this rule to [verified mods repo](https://github.com/R2Northstar/VerifiedMods).

**Comment by Alystrasz** [comment]
This is now up-to-date with `main` branch.
Here is an example of an auto-downloaded (single-player reused) map.

[verified_download_s2space.webm](https://github.com/R2Northstar/NorthstarLauncher/assets/11993538/e5db912c-057c-46a1-9c9e-f66b07687ab5)

**Comment by GeckoEidechse** [comment]
Basically all that is missing for getting this PR merged is statically linking the necessary dlls into `northstar.dll`, right?

**Comment by Alystrasz** [comment]
> Basically all that is missing for getting this PR merged is statically linking the necessary dlls into `northstar.dll`, right?

Yep!
@pg9182 mentioned using [miniz](https://github.com/richgel999/miniz) instead of libzip to address this, so I'd like to try.

**Comment by Alystrasz** [comment]
Ehm, actually, miniz does not expose the same API as libzip at all...
Would including libzip's `.c` and `.h` files solve this issue?

**Comment by Alystrasz** [comment]
Waiting for #500 to be merged before solving conflicts.

I plan to push the [parkour gamemode](https://northstar.thunderstore.io/package/Alystrasz/Parkour/) through the [verification process](https://github.com/R2Northstar/VerifiedMods), and use it as the final example mod for this feature.

**Comment by GeckoEidechse** [comment]
For testing ones own mod it might be useful to have like a command line arg to bypass verification and allow downloading any mod from Thunderstore if the server requires it. I'm fine with having a separate PR for this though afterwards. Just something that came to mind rn ^^

**Comment by Alystrasz** [comment]
> For testing ones own mod it might be useful to have like a command line arg to bypass verification and allow downloading any mod from Thunderstore if the server requires it.

I agree on the principle, however we still need to link mod names to related Thunderstore packages, which can only be done manually...

**Comment by GeckoEidechse** [comment]
> > For testing ones own mod it might be useful to have like a command line arg to bypass verification and allow downloading any mod from Thunderstore if the server requires it.
> 
> I agree on the principle, however we still need to link mod names to related Thunderstore packages, which can only be done manually...

Outside of the scope of this PR but with `packages` we can start parsing Thunderstore stuff natively in Northstar which in turn we could use to expose the required Thunderstore package next to the required mod on server 👀

**Comment by Alystrasz** [comment]
Closing this in favour of a new branch.

**Comment by Alystrasz** [comment]
New version: #545

**Pull request closed without merging**
