### PR TITLE
Localize error messages from masterserver

### PR DESCRIPTION
**Pull request by emma-miler**
Adds this funky little dialog box when failing to authenticate with (master)server

img

Needs to be updated with localization files for all languages

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Merged this and https://github.com/R2Northstar/NorthstarMods/pull/333 locally. Rebuilt launcher in release mode while setting version to `0.0.1.0` to force auth reject based on version number.

However I still just get  "Disconnect: Authentication failed":

snapshot0012

**Comment by ASpoonPlaysGames** [comment]
So i just tested this and was getting the same results as gecko, but ended up getting it working eventually, i didnt have to change anything on the launcher side though, so this PR seems good?

**Comment by Alystrasz** [comment]
Before merging, which keys do you need translated?

**Comment by GeckoEidechse** [comment]
> Before merging, which keys do you need translated?

Keys are

```
NO_GAMESERVER_RESPONSE
BAD_GAMESERVER_RESPONSE
UNAUTHORIZED_GAMESERVER
UNAUTHORIZED_GAME
UNAUTHORIZED_PWD
STRYDER_RESPONSE
PLAYER_NOT_FOUND
INVALID_MASTERSERVER_TOKEN
JSON_PARSE_ERROR
UNSUPPORTED_VERSION
```
altough contrary to the initial PR description, they already appear fully translated in https://github.com/R2Northstar/NorthstarMods/pull/333

**Comment by GeckoEidechse** [comment]
> So i just tested this and was getting the same results as gecko, but ended up getting it working eventually, i didnt have to change anything on the launcher side though, so this PR seems good?

Tried again today and now it worked ¯\\\_(ツ)\_/¯

**Review by RoyalBlue1 — APPROVED** [review]

**Pull request merged**
