### PR TITLE
Retarget to use CMake+Clang/LLVM

### PR DESCRIPTION
**Pull request by emma-miler**
This will need updating of CI before it can build properly.
Will invalidate basically all non-trivial PRs. I'd be happy to help update ones that want to update to the new format.

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
We probably also wanna update CI file before merging.

Also need an update to `BUILD.md` with new instructions ^^

**Comment by emma-miler** [comment]
> We probably also wanna update CI file before merging.
> 
> Also need an update to `BUILD.md` with new instructions ^^

Yes. I will add an update to the build file. I have no experience with CI, so i'm afraid i can't be of much help there.

**Comment by GeckoEidechse** [comment]
> > We probably also wanna update CI file before merging.
> > Also need an update to `BUILD.md` with new instructions ^^
> 
> Yes. I will add an update to the build file. I have no experience with CI, so i'm afraid i can't be of much help there.

That's fine I can look into it.
(Anyone else with CI experience is of course also encouraged to do so, not sure when I'd actually get to it)

**Comment by apophis42** [comment]
Is there a reason my changes from PR #351 are in this PR unattributed?

**Comment by emma-miler** [comment]
> Is there a reason my changes from PR #351 are in this PR unattributed?

Was going to do this on the final commit so it doesnt get buried. Can do it earlier if you want

**Comment by apophis42** [comment]
> > Is there a reason my changes from PR #351 are in this PR unattributed?
> 
> Was going to do this on the final commit so it doesnt get buried. Can do it earlier if you want

Should this not have happened automatically in git if you had based your branch on my fork?

**Comment by pg9182** [comment]
> We probably also wanna update CI file before merging.

I can do that.

**Comment by emma-miler** [comment]
> > > Is there a reason my changes from PR #351 are in this PR unattributed?
> > 
> > 
> > Was going to do this on the final commit so it doesnt get buried. Can do it earlier if you want
> 
> Should this not have happened automatically in git if you had based your branch on my fork?

I didn't do this ^^
Just made my own branch off off main

**Comment by emma-miler** [comment]
This PR currently has a bug where `wsock32.dll` does not get linked correctly. Expected result:
The functions from the `.def` file get linked respecting the ordinal they were given.
image

Actual result:
Ordinals are completely wrong
image

From what i have been able to figure out this has to do with the fact that it is not "forwarding" the external (ws2_32, mswsock) functions correctly. The counting works fine if i only include the proxied functions

**Comment by emma-miler** [comment]
WSock32 will be moved to a separate repo due to issues with building it with non-msvc compilers.
Launcher loader proxy has been removed entirely since we don't ship it anyway

**Comment by emma-miler** [comment]
Will also need to decide on compiler flags like optimization level, warning switches, etc. This can realistically also be done later though.

**Comment by emma-miler** [comment]
Potential bug (needs investigating): `m_pSQVM` seems to point to null on main menu

**Comment by GeckoEidechse** [comment]
AFAIK @emma-miler said she's no longer working on this and we got the CMake part merged with #467

As such I'm closing this to clean up PRs. If anyone wants to pick this up again (and deal with the ungodly amount of merge conflicts) feel free to poke me with a comment here to re-open.

**Pull request closed without merging**
