### PR TITLE
Advanced chat: custom messages and client hooks

### PR DESCRIPTION
**Pull request by cpdt**
Mod changes: https://github.com/R2Northstar/NorthstarMods/pull/217

Features:

 - Server mods can now send chat messages outside of just intercepting incoming ones: this includes impersonating players, sender-less "announcement"/anonymous style messages, and whisper versions of both.
 - The client can intercept incoming chat messages. Client-side chat formatting has been completely replaced by script to open up customisation options.
 - Client mods can display custom announcement messages in the local player's chat.
 - Anonymous messages all support ANSI escape codes for colours, so servers and mods can do fun things like this:
   "Welcome to Northstars of the Crane" shown in rainbow text in the Titanfall 2 lobby chat window

### CODE REVIEW

**Comment by emma-miler** [comment]
Awesome stuff man.
Gonna look into how to make this compatible with commands and mods and stuff ^^

**Comment by emma-miler** [comment]
@GeckoEidechse Currently working on a general API cleanup of the PR and fixing some small issues. Should be ready for 1.5.x

**Comment by cpdt** [comment]
Should be ready to go for real now.

**Comment by emma-miler** [comment]
Awesome, i'll put it on the list for 1.6.0

**Comment by cpdt** [comment]
Just an update on this, we're currently holding out on merging until Emma's improved Squirrel interop is merged.

**Comment by cpdt** [comment]
Improved Squirrel interop is in now so this is good to be merged (once bob’s formatting is fixed ofc).

**Review by abarichello — APPROVED** [review]
LGTM, let's see if @BobTheBob9 has something to add

**Comment by p0358** [comment]
https://github.com/R2Northstar/NorthstarLauncher/blob/main/NorthstarDLL/localchatwriter.cpp#L19-L21

>	// yes these are swapped from the Source 2013 code, who knows why
>	void(__fastcall* InsertStringWide)(vgui_BaseRichText* self, const wchar_t* wszText);
>	void(__fastcall* InsertStringAnsi)(vgui_BaseRichText* self, const char* text);

Answer: MSVC retardation, they swap order of same-named virtual funcs https://twitter.com/p0358/status/1482414127549198338

found the comment when randomly reading code and decided to answer lol

**Pull request merged**
