### PR TITLE
Various minor naming convention fixes

### PR DESCRIPTION
**Pull request by KittenPopo**
I have noticed a few functions here and there that don't comform to Northstar's "established" `PascalCase()` function naming.

I renamed them because it makes the sadness go away.

### CODE REVIEW

**Comment by barnabwhy** [comment]
iirc squirrel functions were both PascalCase cause they were named in correspondence with the functions in squirrel

**Comment by barnabwhy** [comment]
also this undoes at least 1 pr

**Comment by KittenPopo** [comment]
> also this undoes at least 1 pr

What? Which PR?

**Comment by KittenPopo** [comment]
> iirc squirrel functions were both PascalCase cause they were named in correspondence with the functions in squirrel

They... weren't pascal case? Ig if they're corresponding to squirrel funcs maybe do `SQFn_func_name `or somethin'?

**Review by uniboi — APPROVED** [review]
image
less go

**Pull request closed without merging**
