### PR TITLE
Call module callbacks for nested imported modules (i.e `mileswin64.dll`)

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
Mostly ported from 368f66043c6b908dc93ec29f3e856beaaabf6df5 with some modifications to the recursion

### CODE REVIEW

**Review by F1F7Y — APPROVED** [review]
Changes look a-okay

**Comment by F1F7Y** [comment]
Considering one can't really test this and it shouldn't break anything I'll just merge so the dependant PRs can get tested :3

**Comment by GeckoEidechse** [comment]
So this might have broken something https://discord.com/channels/920776187884732556/942505193893945394/1278014298630787194

**Comment by GeckoEidechse** [comment]
Confirmed that reverting this change fixes the particular case mentioned above.

**Comment by GeckoEidechse** [comment]
Mods used by the player experiencing the crash

image
image

**Comment by GeckoEidechse** [comment]
Potentially fixed by #785. Being investigated rn

**Comment by Gazyi** [comment]
Still crashes with #785 applied (1.27.4-rc1)
```
[2024-08-28] [01:06:41] [NORTHSTAR] [info] NorthstarLauncher version: 1.27.4.0
[2024-08-28] [01:06:41] [NORTHSTAR] [info] Command line: "I:\Games\Titanfall2\NorthstarLauncher.exe" 
[2024-08-28] [01:06:41] [NORTHSTAR] [info] Using profile: R2Northstar
[2024-08-28] [01:06:41] [NORTHSTAR] [info] Operating System: Windows (NT6.1)
[2024-08-28] [01:06:41] [NORTHSTAR] [info] Enabling hook _GetCommandLineA
[2024-08-28] [01:06:41] [PLUGINSYS] [warning] Could not find any plugins. Skipped loading plugins
[2024-08-28] [01:06:41] [NORTHSTAR] [info] Enabling hook GetGameLanguage
[2024-08-28] [01:06:41] [NORTHSTAR] [error] -------------------------------------------
[2024-08-28] [01:06:41] [NORTHSTAR] [error] Northstar has crashed!
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Version: 1.27.4.0
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	EXCEPTION_ACCESS_VIOLATION
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Attempted to read from: 0x7fefbd4ffff
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	At: Northstar.dll + 0x291135
[2024-08-28] [01:06:41] [NORTHSTAR] [error] Callstack:
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Northstar.dll + 0x291135
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Northstar.dll + 0x28fe60
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Northstar.dll + 0x237555
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Northstar.dll + 0x2378a6
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	WSOCK32.dll + 0x5c9ab
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	WSOCK32.dll + 0x5ce1e
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	WSOCK32.dll + 0x535f4
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	WSOCK32.dll + 0x4f7bd
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	WSOCK32.dll + 0x4ceb5
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	WSOCK32.dll + 0x4c98a
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	WSOCK32.dll + 0x4cb6f
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	ntdll.dll + 0x37c3e
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	ntdll.dll + 0xfe4d4
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	ntdll.dll + 0xead7d
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	KERNELBASE.dll + 0xb39a
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Northstar.dll + 0x237896
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	NorthstarLauncher.exe + 0x11704
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	NorthstarLauncher.exe + 0x4d4ac
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	kernel32.dll + 0x1556d
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	ntdll.dll + 0x5372d
[2024-08-28] [01:06:41] [NORTHSTAR] [error] Registers:
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Flags:: 0b100000000000001011111
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Rax: 0xffff
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Rcx: 0x3e105a0
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Rdx: 0x7fefbd4ffff
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Rbx: 0x97f170
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Rsp: 0x97ef10
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Rbp: 0x400
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Rsi: 0x7fefbd42000
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Rdi: 0x7fefbd4000c
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	R8 : 0x0
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	R9 : 0x0
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	R10: 0x7fede838850
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	R11: 0x3df1f50
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	R12: 0x0
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	R13: 0x7fedc4548a0
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	R14: 0xffffffffffffffff
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	R15: 0x7fefbd401d0
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Rip: 0x7fedcb91135
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Xmm0 : [ 0, 0, 0, 0 ]; [ 0x0, 0x0, 0x0, 0x0 ]
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Xmm1 : [ 6, 0, 15, 0 ]; [ 0x6, 0x0, 0xf, 0x0 ]
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Xmm2 : [ 1.66818E+09, 8.29173E+08, 8.08268E+08, 1.28007E+09 ]; [ 0x636e7973, 0x316c2d68, 0x302d322d, 0x4c4c442e ]
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Xmm3 : [ 0, 0, 0, 0 ]; [ 0x0, 0x0, 0x0, 0x0 ]
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Xmm4 : [ 0, 0, 0, 0 ]; [ 0x0, 0x0, 0x0, 0x0 ]
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Xmm5 : [ 0, 0, 0, 0 ]; [ 0x0, 0x0, 0x0, 0x0 ]
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Xmm6 : [ 0, 0, 0, 0 ]; [ 0x0, 0x0, 0x0, 0x0 ]
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Xmm7 : [ 0, 0, 0, 0 ]; [ 0x0, 0x0, 0x0, 0x0 ]
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Xmm8 : [ 0, 0, 0, 0 ]; [ 0x0, 0x0, 0x0, 0x0 ]
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Xmm9 : [ 0, 0, 0, 0 ]; [ 0x0, 0x0, 0x0, 0x0 ]
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Xmm10: [ 0, 0, 0, 0 ]; [ 0x0, 0x0, 0x0, 0x0 ]
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Xmm11: [ 0, 0, 0, 0 ]; [ 0x0, 0x0, 0x0, 0x0 ]
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Xmm12: [ 0, 0, 0, 0 ]; [ 0x0, 0x0, 0x0, 0x0 ]
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Xmm13: [ 0, 0, 0, 0 ]; [ 0x0, 0x0, 0x0, 0x0 ]
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Xmm14: [ 0, 0, 0, 0 ]; [ 0x0, 0x0, 0x0, 0x0 ]
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Xmm15: [ 0, 0, 0, 0 ]; [ 0x0, 0x0, 0x0, 0x0 ]
[2024-08-28] [01:06:41] [NORTHSTAR] [error] Loaded Plugins:
[2024-08-28] [01:06:41] [NORTHSTAR] [error] Loaded modules:
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	NorthstarLauncher.exe
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	ntdll.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	kernel32.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	KERNELBASE.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	SHLWAPI.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	GDI32.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	USER32.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	LPK.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	USP10.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	msvcrt.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	ADVAPI32.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	sechost.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	RPCRT4.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	WS2_32.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	NSI.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	IMM32.DLL
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	MSCTF.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	api-ms-win-core-synch-l1-2-0.DLL
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	tier0.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	OriginSDK.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	PSAPI.DLL
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	MSVCR110.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	MSVCP110.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	WINMM.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	Northstar.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	CRYPT32.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	MSASN1.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	dbghelp.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	bcrypt.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	secur32.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	SSPICLI.DLL
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	iphlpapi.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	WINNSI.DLL
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	launcher.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	SHELL32.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	ole32.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	WSOCK32.dll
[2024-08-28] [01:06:41] [NORTHSTAR] [error] 	vstdlib.dll
```

**Comment by GeckoEidechse** [comment]
@Gazyi can you send the corresponding nsdump as well?

**Comment by GeckoEidechse** [comment]
Potentially fixed by #790 
Waiting on someone that can reproduce the bug to test it atm..

**Pull request merged**
