### PR TITLE
Reorganize third-party dependencies into `thirdparty` directory

### LINKED ISSUE #484: 2 copies of MinHook?
there are currently 2 copies of MinHook vendored in NorthstarLauncher:
- [include/MinHook.x64.lib](https://github.com/R2Northstar/NorthstarLauncher/blob/main/include/MinHook.x64.lib)
- [loader_wsock32_proxy/include/MinHook.x64.lib](https://github.com/R2Northstar/NorthstarLauncher/blob/main/loader_wsock32_proxy/include/MinHook.x64.lib)

Was this an oversight or are these two different versions?

### PR DESCRIPTION
**Pull request by F1F7Y**
Everyone does it, we should too ( also not much of an include folder if it has compiled libs now is it )

Closes #484

### CODE REVIEW

**Review by pg9182 — CHANGES_REQUESTED** [review]
While we're at it, can we also remove the unused libraries and reorganize the thirdparty dir to contain a subdir for each individual dependency?

**Comment by F1F7Y** [comment]
> While we're at it, can we also remove the unused libraries and reorganize the thirdparty dir to contain a subdir for each individual dependency?

Wanted to do this in a separate Pr but can do it i this one if you want

**Comment by F1F7Y** [comment]
> While we're at it, can we also remove the unused libraries and reorganize the thirdparty dir to contain a subdir for each individual dependency?

My morning self didnt read this fully. Imo removing unused libraries should be a separate PR from this

**Review by pg9182 — APPROVED** [review]
Good enough for this PR. Internal shouldn't be it's own folder, and ideally, we'd have a separate include dir for each dep, but we're going to be removing it anyways and this is an improvement over the old layout.

**Comment by pg9182** [comment]
Ah, fuck, I was a bit trigger-happy. We also need to update the `.gitattributes` file too.

**Comment by GeckoEidechse** [comment]
> Ah, fuck, I was a bit trigger-happy. We also need to update the `.gitattributes` file too.

Made PR for it in #496

**Pull request merged**
