### PR TITLE
Remove uses of Autohook from `dedicated.cpp`

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
### Code review:
- The original function is prefixed with `o_p` so any times where the old AUTOHOOK was calling the original function it should now be calling that instead.
- The hook function is prefixed with `h_` so any times where we would be wanting to call the hooked function from other functions should now be calling that instead

### Testing:
- Check logs to make sure that all of the changed hooks are being created properly
- Make sure that dedicated servers still gracefully close on script error instead of hard crashing.

### CODE REVIEW

**Review by F1F7Y — APPROVED** [review]
Changes look good

**Comment by GeckoEidechse** [comment]
> Make sure that dedicated servers still gracefully close on script error instead of hard crashing.

Do we have an easy way to script crash via some script function? Or do we need to write like a broken mod to test this >.<

**Comment by ASpoonPlaysGames** [comment]
> Do we have an easy way to script crash via some script function? Or do we need to write like a broken mod to test this >.<

The latter I think. Iirc any error induced by a simple `script` command is non-fatal, so youd have to introduce a logic (not compile) error into the scripts and trigger it

**Review by F1F7Y — APPROVED** [review]
Works in testing

**Pull request merged**
