### PR TITLE
LatencyFleX Implementation

### PR DESCRIPTION
**Pull request by KyleGospo**
Adds LatencyFleX, an open source and vendor agnostic input latency reduction technology similar to Nvidia's Reflex. Currently only works on Linux via Wine/Proton, but future versions may support Windows as well. Falls back to doing nothing if LatencyFleX isn't available.

See here for more information:
https://ishitatsuyuki.github.io/post/latencyflex/

### CODE REVIEW

**Comment by laundmo** [comment]
When you say thisnworks in Proton, does that mena it works on just Proton or Wine too?

as far as i understand this affects the rendering, do you know whether that is relevant for Dedicated Servers?

**Comment by KyleGospo** [comment]
Completely irrelevant for Dedicated servers, it works with normal Wine as well so long as you install LatencyFleX

**Comment by abarichello** [comment]
Can you provide data that this is indeed worth integrating into the project? I tried running your patch with their [custom mangohud config](https://github.com/ishitatsuyuki/LatencyFleX#mangohud-with-metric-support-optional) to graph latency but I couldn't get it to work, the graph just flatlines to zero when playing the game.

**Comment by KyleGospo** [comment]
Can you add one of your logs with this enabled? To be clear, you did also add LFX=1 to your launch options, right?

**Comment by KyleGospo** [comment]
Alright, took me a minute to get the best possible demonstration of this due to my CPU/GPU combo, but here we go:

With adaptive supersampling enabled and an FPS target of 5 and LatencyFleX disabled, I get 100% GPU usage with a fairly flat frametime:
Screenshot from 2022-01-11 14-06-20

Here is that same scene with LatencyFleX enabled, as you can see the GPU usage has dropped (To around the 95% number that is expected), and the frametime is now more variable (introduced jitter) as it tries to keep the frame queue clear.
Screenshot from 2022-01-11 14-06-53

You can also see evidence of it working when minimizing the game, with a low framerate upon returning until the algorithm is able to self-correct. I consider this a bug and am working to correct it.
Screenshot from 2022-01-11 14-07-16

**Comment by KyleGospo** [comment]
The alt+tab bug mentioned above is now fixed upstream, no changes needed on our side.

**Review by abarichello — APPROVED** [review]
LGTM, I just need you to introduce a new section to the wiki explaining LatencyFlex and how to use it on Linux

**Comment by KyleGospo** [comment]
Pull request created for the wiki at:
https://github.com/R2Northstar/NorthstarWiki/pull/18

**Pull request merged**
