### PR TITLE
Hidden console stuff

### PR DESCRIPTION
**Pull request by barnabwhy**
console is visible until game window opens
`-showconsole` startup arg keeps console open
`show_console_window` convar allows the console to be opened and closed at runtime
console always stays open on dedicated servers
hides the game window and displays the console on crash
~~parents crash message box to the console~~ this made it not make the message box and just crash with an error noise if you clsoed the console

### CODE REVIEW

**Comment by barnabwhy** [comment]
I need to hook engine error and show console when that happens

**Comment by barnabwhy** [comment]
fuck i broke something

**Comment by GeckoEidechse** [comment]
Merge conflicts :trollface:

**Comment by GeckoEidechse** [comment]
Any chance you could resolve merge conflicts? Squash and rebase maybe? Hidden console is a lot nicer than how we have it currently. In fact console showing even causes issue in cases like when using gamescope on Linux. So hiding console is something we should do in the nearer future for polish.

**Comment by uniboi** [comment]
@barnabwhy when the merge has conflicts

**Comment by uniboi** [comment]
forgotten pr 💀

**Comment by barnabwhy** [comment]
> forgotten pr 💀

not forgotten just not being done :trollface:

**Comment by emma-miler** [comment]
Superceded by #332

**Pull request closed without merging**
