### PR TITLE
Remove uses of Autohook from `audio.cpp`

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
Trying to move towards manual hooks over macro hell, one file at a time.

Requires:
- #780

### Code review:
- The original function is prefixed with `o_p` so any times where the old AUTOHOOK was calling the original function it should now be calling that instead.
- The hook function is prefixed with `h_` so any times where we would be wanting to call the hooked function from other functions should now be calling that instead

### Testing:
- Check logs to make sure that all of the changed hooks are being created properly
- Load an audio mod and see if it still works I guess?

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Part of #778

**Review by F1F7Y — APPROVED** [review]
Changes look ok, however this isnt going to work in testing as `mileswin64.dll` is imported by `client.dll` and we only run callbacks for `LoadLibrary*` calls. ( See this change in primedev: https://github.com/F1F7Y/NorthstarPrime/commit/368f66043c6b908dc93ec29f3e856beaaabf6df5#diff-54ccaa9ecaf9f49dd1e7d51bfe382cb5025349aee6cd4a3003282314a99d19ad )

**Comment by F1F7Y** [comment]
(Approved because this'll fail when testing, meh)

**Review by GeckoEidechse — CHANGES_REQUESTED** [review]
As @F1F7Y predicted, this breaks in testing.

Tested with https://thunderstore.io/c/northstar/p/FUZE/Replace_Background_Music_for_The_Lobby_with_Helldivers2_OST/

Without the PR the lobby music was overridden, with the PR it no longer was.

**Comment by ASpoonPlaysGames** [comment]
Now depends on #780

**Review by GeckoEidechse — APPROVED** [review]
Confirmed working testing. My death sound audio override mod still worked.

**Review by F1F7Y — APPROVED** [review]
No changes to code, fix is already on main. LGTM

**Pull request merged**
