### PR TITLE
Memory class renaming

### PR DESCRIPTION
**Pull request by F1F7Y**
- Renames `MemoryAddress` to `CMemoryAddress`
  - Shorter name and follows naming convention of `CModule`
- Renames `CMemoryAddress::As` to `CMemoryAddress::RCast`
  - imo `RCast` tells the reader more ( from `reinterpret_cast` )

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
@F1F7Y going hard on clean-up/refactor PRs, and I'm absolutely here for it <3

Will spam ping @BobTheBob9 until he looks at it >:)

**Review by BobTheBob9 — CHANGES_REQUESTED** [review]
not sure on CMemory, i think CMemoryAddress maybe but CMemory isn't descriptive enough imo, RCast is a good change though ^^

**Comment by F1F7Y** [comment]
> not sure on CMemory, i think CMemoryAddress maybe but CMemory isn't descriptive enough imo, RCast is a good change though ^^

I went with `CMemory` since it was shorter, but if we're going for descriptive names first I'm all for `CMemoryAddress`

**Comment by BobTheBob9** [comment]
> > not sure on CMemory, i think CMemoryAddress maybe but CMemory isn't descriptive enough imo, RCast is a good change though ^^
> 
> I went with `CMemory` since it was shorter, but if we're going for descriptive names first I'm all for `CMemoryAddress`

i understand why you did it, generally i prefer descriptive and verbose over short if it's not unreasonably long thoight

**Comment by F1F7Y** [comment]
seems like i was right

**Review by BobTheBob9 — APPROVED** [review]
looks good

**Comment by GeckoEidechse** [comment]
Someone like launch game once with the binary from CI, check if it runs, and then we can merge this ^^

**Comment by uniboi** [comment]
It's a class rename, it has literally 0 impact on runtime.
If it compiles it's fine

**Comment by ASpoonPlaysGames** [comment]
> * Renames `MemoryAddress` to `CMemoryAddress`
>   
>   * Shorter name and follows naming convention of `CModule`
> * Renames `CMemoryAddress::As` to `CMemoryAddress::RCast`
>   
>   * imo `RCast` tells the reader more ( from `reinterpret_cast` )

Is this description still accurate?

**Pull request merged**
