### PR TITLE
Maxplayers increase + various QoL fixes and implementations

### PR DESCRIPTION
**Pull request by HappyDOGE**
Changes done:
- Increased maxplayers from 32 to 64 players. (Done by DataTable remapping and various engine fixes, see maxplayers.cpp for detailed information)
- Implemented the print function that status concommand uses, making status available for use by server operators.
- Implemented svc_Print, making various server printouts visible clientside (including status output).
- Implemented a way for dedicated server to receive and process concommands through the console. (toggleable with -noconsoleinput)
- Disabled Quick Edit mode to help prevent accidental server hangs by selecting text from console. (toggleable with -bringbackquickedit)
- Fixed a build error in masterserver.cpp (?)

Note on maxplayers:
- The increase breaks compatibility with both vanilla and old Northstar clients/servers. The -nomaxplayersincrease command line parameter can be used to disable that, however using it is discouraged as it could potentially bring even more discrepancy between clients and servers. Something needs to be done about that.

### CODE REVIEW

**Comment by wolf109909** [comment]
cool

**Comment by wolf109909** [comment]
i mean actually this is so cool lmao

**Comment by HK560** [comment]
”64 players“ sounds crazy . i'm very excited about that

**Comment by BobTheBob9** [comment]
everything here is really great, however i'm likely gonna run tests with the maxplayers tweaks in particular before merging to main if it's potentially unstable, if you'd be down to pull everything except from the maxplayers changes separately for now that'd be awesome

**Comment by HappyDOGE** [comment]
Max players is now disabled by default, and toggleable through the -experimentalmaxplayersincrease command line parameter.
Is that acceptable?

**Comment by pollik3314** [comment]
Hey happy doge How would I go about utilizing the console commands? I can't seem to find a way to do it with a dedicated server. Thanks!

**Comment by HappyDOGE** [comment]
@pollik3314 Make sure you are using this fork and not the main branch as it does not have the console input implemented atm.

**Comment by pollik3314** [comment]
@HappyDOGE thanks for the speedy response! I'm pretty new to coding personally, especially C++ so I really have no idea what that means or how I would go about doing that.

**Comment by HappyDOGE** [comment]
Merged with upstream by request

**Pull request merged**
