### PR TITLE
Use 4th digit in version number for CI build number

### LINKED ISSUE #369: Use 4th digit in version number for CI build number
Currently version number is

```
 1.2.3.0
 ^ ^ ^ ^
 │ │ │ └ dev or not
 │ │ └── patch
 │ └──── minor
 └────── major
```

We could replace the last digit with the build number instead. Given that any non-zero build should be dev, we could change the last digit to build number in CI and would (in theory) not need to change other parts of launcher (unless we also want to send build number to Atlas).

This means we would then have

```
 1.2.3.987654
 ^ ^ ^ ^
 │ │ │ └ build number, zero for release
 │ │ └── patch
 │ └──── minor
 └────── major
```

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
closes #369

example of working CI:
https://github.com/ASpoonPlaysGames/NorthstarLauncher/actions/runs/6076234977

### CODE REVIEW

**Review by pg9182 — COMMENTED** [review]
I like this change (but haven't tested it), but please ping me before merging this.

**Comment by GeckoEidechse** [comment]
Uh, no merge conflict with #542 merged but I guess this PR still needs to be updated so that run number is written to both exe and dll?

Or is this kinda done implicitly already? ^^

**Comment by ASpoonPlaysGames** [comment]
> Uh, no merge conflict with #542 merged but I guess this PR still needs to be updated so that run number is written to both exe and dll?

Correct

**Comment by ASpoonPlaysGames** [comment]
image
another example of successful testing, going to remove the needs testing label

**Review by GeckoEidechse — APPROVED** [review]
Can confirm that version number is set accordingly.

```
$ exiftool Northstar.dll 
ExifTool Version Number         : 12.60
File Name                       : Northstar.dll
...
File Version Number             : 0.0.0.2823
Product Version Number          : 0.0.0.2823
...
```


```
$ exiftool NorthstarLauncher.exe 
ExifTool Version Number         : 12.60
File Name                       : NorthstarLauncher.exe
...
File Version Number             : 0.0.0.2823
Product Version Number          : 0.0.0.2823
...
```

Didn't test running game but based on the changes this should have no impact.

Code changes look fine, comment was also properly updated.
(I'm still annoyed that it's convention in C to drop the `!= 0` and rely on truthiness of integers but that's besides the point :P)

**Pull request merged**
