### PR TITLE
Fix name spoofing

### PR DESCRIPTION
**Pull request by r3muxd**

### CODE REVIEW

**Review by BobTheBob9 — CHANGES_REQUESTED** [review]
this is a great pr conceptually but i'd rather do the verification in authentication or somewhere where the web request isn't going to block main loop

**Comment by barnabwhy** [comment]
If i'm not mistaken all this does is check if the origin username exists, and thus it surely only stops people setting non-existent usernames and not name spoofing as a whole

**Comment by BobTheBob9** [comment]
> If i'm not mistaken all this does is check if the origin username exists, and thus it surely only stops people setting non-existent usernames and not name spoofing as a whole

yeah, but it helps at least, and prevents any invalid origin names from joining at all

**Comment by BobTheBob9** [comment]
closing due to lack of activity

**Pull request closed without merging**
