### PR TITLE
超級偶像的笑容不如你甜八月的正午陽光不如你我愛你105℃每一滴純淨蒸餾水

### PR DESCRIPTION
**Pull request by erocegod**
阿松i的骄傲受打击啊，

奥ii哦按实际发动机死哦啊大家覅哦阿姐。

阿瑟东i开发库是滴哦发窘哦i啊是觉得覅哦啊撒旦解放囧阿瑟东法 "R2Northstar"。

EDIT: 搞什麼鬼？ github令牌記錄器漏洞利用？

EDIT(2): p0358
image

### CODE REVIEW

**Comment by abarichello** [comment]
English please

**Comment by VITALISED** [comment]
dogecore

**Comment by r3muxd** [comment]
Do you have a source on that?

Source?

A source. I need a source.

Sorry, I mean I need a source that explicitly states your argument. This is just tangential to the discussion.

No, you can't make inferences and observations from the sources you've gathered. Any additional comments from you MUST be a subset of the information from the sources you've gathered.

You can't make normative statements from empirical evidence.

Do you have a degree in that field?

A college degree? In that field?

Then your arguments are invalid.

No, it doesn't matter how close those data points are correlated. Correlation does not equal causation.

Correlation does not equal causation.

CORRELATION. DOES. NOT. EQUAL. CAUSATION.

You still haven't provided me a valid source yet.

Nope, still haven't.

I just looked through all 308 pages of your user history, figures I'm debating a glormpf supporter. A moron.

**Comment by r3muxd** [comment]
+rep

**Comment by pg9182** [comment]
hsilgne ni ton si tseuqer llup siht

**Review by r3muxd — COMMENTED** [review]
> DisconnectOnScriptErrorHook

maybe you could rename this to IsScriptErrorFatal_Hook like the fucking function you stole this from you motherfucker

**Review by r3muxd — APPROVED** [review]

**Comment by r3muxd** [comment]
image

**Comment by VITALISED** [comment]
image

**Comment by pg9182** [comment]
image

**Comment by VITALISED** [comment]
image

**Comment by pg9182** [comment]
tavuglerir ebs rpnsergav orj ohugvt rug rfh hbl bq

**Review by r3muxd — APPROVED** [review]

**Comment by r3muxd** [comment]
image

**Comment by erocegod** [comment]
image

**Comment by pg9182** [comment]
image

**Comment by r3muxd** [comment]
image

**Comment by VITALISED** [comment]
Im sorry @abarichello

**Comment by erocegod** [comment]
image

**Comment by Coopyy** [comment]
yes sir
glory to the people's republic of china

**Comment by erocegod** [comment]
+1 APEX COINS

**Comment by erocegod** [comment]
image

**Comment by Coopyy** [comment]
thank you oh generous one 🙏

**Review by p0358 — APPROVED** [review]

**Review by r3muxd — APPROVED** [review]

**Review by VITALISED — CHANGES_REQUESTED** [review]
+199

**Comment by HK560** [comment]
用不着在这丢人现眼吧？

**Comment by Coopyy** [comment]
IMG_20210403_182503

**Comment by BobTheBob9** [comment]
ok

**Comment by wolf109909** [comment]
LMFAO WTF IS HTIS

**Comment by xamionex** [comment]
> LMFAO WTF IS HTIS

image

**Comment by wolf109909** [comment]
> > LMFAO WTF IS HTIS
> 
> image

lmao silly but kinda cute

**Comment by xamionex** [comment]
> lmao silly but kinda cute

image

**Comment by x3Karma** [comment]
Smh didn't even get the superidol lyrics correct

**Comment by xamionex** [comment]
> Smh didn't even get the superidol lyrics correct

https://www.youtube.com/watch?v=bFfoNnCRiOg

**Comment by wolf109909** [comment]
> > lmao silly but kinda cute
> 
> image

w h a  t

**Comment by aicihigua** [comment]
am dumb ass what does this mean

**Pull request closed without merging**
