### PR TITLE
UserCMD processing reset bug

### PR DESCRIPTION
**Pull request by GeckoEidechse**
Spliced out from #193 

Should also include grapple fixes.

### CODE REVIEW

**Comment by KittenPopo** [comment]
This fixes more than just the grapple bug, including thirdperson in custom modded gameplay and probably other things I cannot remember off the top of my head.

Consider renaming this to "UserCMD processing reset bug" or such, as that's the core problem I fixed.

**Comment by GeckoEidechse** [comment]
Welp, it doesn't seem to work as intended anyway as it still disconnects grapple. The player grappling is unintentionally forced to turn to 0,0,0 it seems. Like the person grappling in this clip did not move their mouse yet they still turn.

https://user-images.githubusercontent.com/40122905/173956979-225fe190-e232-4b23-9b3c-a4f27da37939.mp4

**Comment by KittenPopo** [comment]
> Welp, it doesn't seem to work as intended anyway as it still disconnects grapple. The player grappling is unintentionally forced to turn to 0,0,0 it seems. Like the person grappling in this clip did not move their mouse yet they still turn.

Damn alright, I think I know how to fix this, lemme make a PR lol.

**Comment by GeckoEidechse** [comment]
Superseded by #203

**Pull request closed without merging**
