### PR TITLE
Remove uses of Autohook from `languagehooks.cpp`

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
### Code review:
- The original function is prefixed with `o_p` so any times where the old AUTOHOOK was calling the original function it should now be calling that instead.
- The hook function is prefixed with `h_` so any times where we would be wanting to call the hooked function from other functions should now be calling that instead

### Testing:
- Check logs to make sure that all of the changed hooks are being created properly
- Make sure that the logging in the language hooks still triggers and behaves normally.

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
Not sure how to test this cause I cannot even get current main to switch the language when setting the game to German in Steam and then using either `-lanuage=english` or `-lanuage english`...

What do you think would be the best way to proceed?

**Review by F1F7Y — APPROVED** [review]
Changes to code look good :rabbit:

**Comment by F1F7Y** [comment]
> Not sure how to test this cause I cannot even get current main to switch the language when setting the game to German in Steam and then using either `-lanuage=english` or `-lanuage english`...
> 
> What do you think would be the best way to proceed?

Merge it and make a tracking issue or bother someone who can step through the code :)

**Comment by GeckoEidechse** [comment]
Made issue via #778 

I guess we just YOLO this one otherwise. Like ideally we'd fix the hook first and then replace the macro as it _should_ be easier to bisect the change that broke it in this case. That being said, I also don't wanna stall the process of removing the autohook macro so I'm merging despite not having a way to verify in testing that the change is correct.

**Pull request merged**
