### PR TITLE
Expose Cursor Position to sq vm

### PR DESCRIPTION
**Pull request by uniboi**
UI can do cool things with the cursor position.

```cpp
array<int> NSGetCursorPosition()
```
returns position as [x,y] in pixel relative to the game window origin.

Depends on https://github.com/R2Northstar/NorthstarLauncher/pull/343

### CODE REVIEW

**Comment by Erlite** [comment]
Might want to change the branch to main, makes it hard to figure out your changes over the others.

**Comment by uniboi** [comment]
literally click the link https://github.com/R2Northstar/NorthstarLauncher/pull/375/commits/d628d87d91e44c8c18412c5ac32f1dc21ec8fd42

**Comment by Erlite** [comment]
I'm memeing, you did the same to my HTTP PR.

Code looks good to me, can probably be merged once Emma's PR is in.

**Comment by RoyalBlue1** [comment]
why not return a struct with 2 ints? you need to add the struct in the init.nut though

**Comment by ASpoonPlaysGames** [comment]
Whats the interaction with users who are tabbed out of the game? Want to avoid ui clicks "through" other windows

**Comment by uniboi** [comment]
> why not return a struct with 2 ints? you need to add the struct in the init.nut though

because a) I forgor that's possible b) my c++ experience is limited to Hello World and c) GetScreenSize() gives an array back as well

> Whats the interaction with users who are tabbed out of the game? Want to avoid ui clicks "through" other windows

positions are relative to the game window origin, so if you're on your second position your x position might be 2000 for example

**Comment by ASpoonPlaysGames** [comment]
> positions are relative to the game window origin, so if you're on your second position your x position might be 2000 for example

That's not really what i mean. Windows can be overlayed on top of each other so there is a chance that when using a second window, the position could still be being used (when it shouldn't really)

**Comment by ASpoonPlaysGames** [comment]
image
for example, when im tabbed into file explorer, Apex shouldn't be getting my cursor position and returning a value that apex cares about

**Comment by uniboi** [comment]
yeah no I don't check if the game is in focus or whatever, I just get the cursor position

**Comment by ASpoonPlaysGames** [comment]
Probably should return a null value of some kind when the game isn't in focus, some people use virtual keyboards and stuff so tracking mouse positions all the time could be seen as a security vulnerability

**Comment by emma-miler** [comment]
Rebase on current main, cherrypick the changes you need, and make a new PR. Also, return a vector instaed

**Pull request closed without merging**
