### PR TITLE
Folder restructuring from primedev

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
Has to cherry pick by hand because github is dumb but yeah

Cherry picking ccf5772e6f09432d23c4712b03e43d4433d6f08a

### CODE REVIEW

**Comment by ASpoonPlaysGames** [comment]
Completely untested btw, so yeah

**Comment by GeckoEidechse** [comment]
I have some concerns with renaming `NorthstarDLL` to `primedev` as to both existing and new contributors, the folder rename might add extra confusion.

That being said, I'm okay with forgoing those concerns by accepting the change on the short-term in order to more easily keep merging changes from `primedev`.

I'd love to also here the input from people who currently have PRs open, as they will be affected by this in the shape of merge conflicts. In particular I'd love some input from:

- @uniboi (plugin interfaces #615  )
- @Jan200101 (`structs.h` refactor #613 )
- @F1F7Y (original author of the change + a bunch of open PRs)
- @catornot ( #604 )

**Comment by uniboi** [comment]
#613 adds files so it should be merged after this pr

**Comment by F1F7Y** [comment]
I dont think this is the correct path to take.

You'll get very little benefit from just moving files around without modifying their contents.

**Comment by uniboi** [comment]
cherry picking more is going to be a pain without this commit though

**Comment by F1F7Y** [comment]
> cherry picking more is going to be a pain without this commit though

I never said you should cherry pick differently or that you should cherry pick at all. I also never said primedev was finished or more stable.

**Comment by GeckoEidechse** [comment]
@F1F7Y I thought the idea was to carry over logical changes from primedev into Northstar in order to get the _good parts_ of primedev in Northstar?

What would be your suggestion in order to get (parts of) primedev in Northstar? ^^

**Comment by F1F7Y** [comment]
> @F1F7Y, I thought the idea was to carry over logical changes from primedev into Northstar in order to get the _good parts_ of primedev in Northstar?
> 
> What would be your suggestion in order to get (parts of) primedev in Northstar? ^^

My suggestion would be to rewrite Northstar and release a 2.0 version. This obviously requires talent and time Northstar doesn't have currently.

Northstar Prime is me giving up on Northstar but not wanting everything i learnt go to waste. At the time the logical solution i saw was to make a fork and work on it without having to worry about PRs or having any broad discussions. After a few months of work i got burnt out, hence why I don't recommend copy pasting primedev as there's a bunch of temporary solutions that were done to make it easier to restructure entire systems.

**Comment by GeckoEidechse** [comment]
Hmmm, aight. Any suggestions what you'd change in Northstar for 2.0 refactor or the like? Maybe we can get those worked on and figured out together.

Feel free to drop them here, in a new Github issue/discussion, or just directly in my DMs. Whatever works best <3

**Comment by F1F7Y** [comment]
> Hmmm, aight. Any suggestions what you'd change in Northstar for 2.0 refactor or the like? Maybe we can get those worked on and figured out together.
> 
> Feel free to drop them here, in a new Github issue/discussion, or just directly in my DMs. Whatever works best <3

Most things others have already been saying for months. Better plugin system, better mod system, more developer focused features such as debug navmesh rendering, etc...

**Comment by GeckoEidechse** [comment]
> Most things others have already been saying for months. Better plugin system, better mod system, more developer focused features such as debug navmesh rendering, etc...

Yeah, unfortunately, in the information blackhole that is Discord, stuff gets lost quite easily, hence I tend to push for more discussion on GitHub.

That being said:

- **Better plugin system** -> #615 (if you got any more suggestions on that etc, please drop a message there or LMK somewhere else)
- **better mod system** -> There's https://github.com/R2Northstar/Northstar/issues/472 which mainly resulted in the introduction of `packages`. Might be worth making a new issue for further improvements.
- **more developer focused features such as debug navmesh rendering** -> Now tracking via https://github.com/R2Northstar/Northstar/discussions/608
- **etc...** -> if you got any more ideas LMK <3

**Review by GeckoEidechse — COMMENTED** [review]
I like the move to subdir but not so much the moving of launcher into subdir of DLL as to my knowledge the two are not that tightly coupled.

That being said, I'm aware that a temporary change to mimic primedev will help a lot in getting stuff moved over.

Proper code review + test tbd.

**Comment by ASpoonPlaysGames** [comment]
> I like the move to subdir but not so much the moving of launcher into subdir of DLL as to my knowledge the two are not that tightly coupled.

IMO it would be a bit dumb to have DLL in its own subfolder within the base folder, because like 95% of the codebase is DLL and having to go an extra folder deep to access the vast majority of things is not great.

(also i believe primedev has them a bit more tightly coupled later down the line, with launcher doing the logging and stuff or something)

**Review by GeckoEidechse — APPROVED** [review]
So, from looking at far as I can tell it's all just the file move as expected.
(I already voiced my opinion on the change so I'm not gonna repeat it again)

As for testing, there's not much to test as it's just a file move so if it compiles fine it should just work™
(I still launched client once just in case lol)

**Comment by GeckoEidechse** [comment]
Already sorry in advance to everyone having a PR open rn ^^"

**Pull request merged**
