### PR TITLE
Remove uses of Autohook from `latencyflex.cpp`

### PR DESCRIPTION
**Pull request by ASpoonPlaysGames**
### Code review:
- The original function is prefixed with `o_p` so any times where the old AUTOHOOK was calling the original function it should now be calling that instead.
- The hook function is prefixed with `h_` so any times where we would be wanting to call the hooked function from other functions should now be calling that instead

### Testing:
- Check logs to make sure that all of the changed hooks are being created properly
- Make sure that the convar `r_latencyflex` works as usual

### CODE REVIEW

**Comment by GeckoEidechse** [comment]
`r_latencyflex` doesn't show up for me on `main`. I assume it only does when actually running LatencyFlex? Honestly this is gonna be a pain to test so if @F1F7Y says the code is fine, I'd propose to merge and immediately release afterwards to test in prod instead.

**Comment by F1F7Y** [comment]
`r_latencyflex` should always show up on client. I'll look into it when I get home ( in ~4h )

**Comment by F1F7Y** [comment]
I forgor 💀

**Review by F1F7Y — APPROVED** [review]
Changes look good :fish:

**Comment by F1F7Y** [comment]
not seeing `r_latencyflex` means the dll load callback just isnt getting called or its returning here https://github.com/R2Northstar/NorthstarLauncher/blob/c8b7bb0f41f04119492a46c41d55e27d7eeb6f5a/primedev/client/latencyflex.cpp#L31-L32 which also logs so would be cool if you could check logs @GeckoEidechse if you have time.

Reading the check the convar only exists when either `latencyflex_layer.dll` or `latencyflex_wine.dll` exist.

**Review by GeckoEidechse — APPROVED** [review]
The line @F1F7Y mentioned still shows up using this PR so I guess it works. Unfortunately I don't have a LatencyFlex setup to test this further so this must do ig.

```
[2024-08-31] [11:32:02] [NORTHSTAR] [info] Unable to load LatencyFleX library, LatencyFleX disabled.
```

**Pull request merged**
